version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: twin-ai-api
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    command: uvicorn src.server.api_server:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
    depends_on:
      - chroma-db
    networks:
      - twinai-net

  slackbot:
    build:
      context: .
      dockerfile: Dockerfile.slackbot
    container_name: twin-ai-slackbot
    environment:
      - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN}
      - SLACK_APP_TOKEN=${SLACK_APP_TOKEN}
      - API_SERVER_URL=http://api:8000/ask
    command: python src/slackbot/bot.py
    depends_on:
      - api
    restart: unless-stopped
    networks:
      - twinai-net

  chroma-db:
    image: ghcr.io/chroma-core/chroma:latest
    container_name: chroma-db
    ports:
      - "8001:8000"
    volumes:
      - index_data:/chroma/.chroma/index
    networks:
      - twinai-net

volumes:
  index_data:
    driver: local

networks:
  twinai-net:
    driver: bridge
