FROM python:3.12-slim
WORKDIR /app
RUN apt-get update && apt-get install -y ca-certificates && update-ca-certificates
RUN pip install --upgrade pip && pip install poetry
COPY . .
RUN poetry config virtualenvs.create false && poetry install --no-interaction --no-ansi
CMD ["python", "src/slackbot/bot.py"]
