FROM python:3.12-slim
WORKDIR /app
RUN apt-get update && apt-get install -y ca-certificates && update-ca-certificates
RUN pip install --upgrade pip && pip install poetry
COPY . .
RUN poetry config virtualenvs.create false && poetry install --no-interaction --no-ansi
CMD ["uvicorn", "src.server.api_server:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
