# Generated by Django 5.2.3 on 2025-06-17 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("document", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ObsidianFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_path", models.CharField(max_length=1024, unique=True)),
                ("file_name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Obsidian File",
                "verbose_name_plural": "Obsidian Files",
                "db_table": "obsidian_files",
            },
        ),
        migrations.AddField(
            model_name="document",
            name="obsidian_file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="document.obsidianfile",
            ),
        ),
    ]
